### ISSUE TITLE
Update for version 1.21.4

### ISSUE THREAD

**Issue by gabriel-gledhill** [scriptmunkeeofficial/MacOS-Optimized#6]
Support for recent version requested according to instructions on Modrinth page.

**Comment by scriptmunkeeofficial** [comment]
Hi @gabriel-gledhill , thanks for the request. I'll look to add support for 1.21.4 in the next few days.

If you have any other feedback or requests, please don't hesitate to ask.

**Comment by gabriel-gledhill** [comment]
Thank you.

**Comment by scriptmunkeeofficial** [comment]
Support for 1.21.4 has been released. Go to https://modrinth.com/modpack/macos-optimized/version/1.1.2
